"""bookings renter index

Revision ID: 0984069369d4
Revises: 8338c2bbed32
Create Date: 2026-02-13 16:17:19.898364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0984069369d4'
down_revision: Union[str, Sequence[str], None] = '8338c2bbed32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_renter_id', 'bookings', ['renter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_renter_id', table_name='bookings')
    # ### end Alembic commands ###
