"""booking overlap index

Revision ID: 58a1db0ebfc7
Revises: 25a365d1ce8b
Create Date: 2026-02-13 15:48:30.468423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a1db0ebfc7'
down_revision: Union[str, Sequence[str], None] = '25a365d1ce8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_car_id'), 'bookings', ['car_id'], unique=False)
    op.create_index('ix_bookings_car_status_dates', 'bookings', ['car_id', 'status', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_bookings_end_date'), 'bookings', ['end_date'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_renter_id'), 'bookings', ['renter_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_date'), 'bookings', ['start_date'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_renter_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_date'), table_name='bookings')
    op.drop_index('ix_bookings_car_status_dates', table_name='bookings')
    op.drop_index(op.f('ix_bookings_car_id'), table_name='bookings')
    # ### end Alembic commands ###
