"""booking overlap index

Revision ID: 7a4b81ee6522
Revises: 58a1db0ebfc7
Create Date: 2026-02-13 15:51:28.731975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4b81ee6522'
down_revision: Union[str, Sequence[str], None] = '58a1db0ebfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_car_id', table_name='bookings')
    op.drop_index('ix_bookings_end_date', table_name='bookings')
    op.drop_index('ix_bookings_id', table_name='bookings')
    op.drop_index('ix_bookings_renter_id', table_name='bookings')
    op.drop_index('ix_bookings_start_date', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_start_date', 'bookings', ['start_date'], unique=False)
    op.create_index('ix_bookings_renter_id', 'bookings', ['renter_id'], unique=False)
    op.create_index('ix_bookings_id', 'bookings', ['id'], unique=False)
    op.create_index('ix_bookings_end_date', 'bookings', ['end_date'], unique=False)
    op.create_index('ix_bookings_car_id', 'bookings', ['car_id'], unique=False)
    # ### end Alembic commands ###
