"""extend cars listing fields

Revision ID: dc2d846db9f9
Revises: 189367b2733f
Create Date: 2026-02-17 15:39:44.399347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2d846db9f9'
down_revision: Union[str, Sequence[str], None] = '189367b2733f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Add columns (nullable first)
    op.add_column("cars", sa.Column("city", sa.String(), nullable=True))
    op.add_column("cars", sa.Column("postcode", sa.String(), nullable=True))
    op.add_column("cars", sa.Column("transmission", sa.String(), nullable=True))
    op.add_column("cars", sa.Column("fuel_type", sa.String(), nullable=True))
    op.add_column("cars", sa.Column("seats", sa.Integer(), nullable=True))
    op.add_column("cars", sa.Column("doors", sa.Integer(), nullable=True))
    op.add_column("cars", sa.Column("mileage", sa.Integer(), nullable=True))
    op.add_column("cars", sa.Column("color", sa.String(), nullable=True))
    op.add_column("cars", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("cars", sa.Column("features", sa.JSON(), nullable=True))

    # 2) Backfill existing rows (so we can enforce NOT NULL safely)
    op.execute(
        """
        UPDATE cars
        SET
          city = COALESCE(city, 'Bristol'),
          postcode = COALESCE(postcode, 'BS1'),
          transmission = COALESCE(transmission, 'AUTOMATIC'),
          fuel_type = COALESCE(fuel_type, 'PETROL'),
          seats = COALESCE(seats, 5),
          doors = COALESCE(doors, 5),
          mileage = COALESCE(mileage, 0),
          color = COALESCE(color, 'Grey'),
          features = COALESCE(features, '{}'::json)
        """
    )

    # 3) Enforce NOT NULL for key “real listing” fields
    op.alter_column("cars", "city", nullable=False)
    op.alter_column("cars", "postcode", nullable=False)
    op.alter_column("cars", "transmission", nullable=False)
    op.alter_column("cars", "fuel_type", nullable=False)
    op.alter_column("cars", "seats", nullable=False)
    op.alter_column("cars", "doors", nullable=False)
    op.alter_column("cars", "mileage", nullable=False)
    op.alter_column("cars", "color", nullable=False)

    # 4) Optional: set server default for features to '{}'
    op.alter_column("cars", "features", server_default=sa.text("'{}'::json"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'features')
    op.drop_column('cars', 'description')
    op.drop_column('cars', 'color')
    op.drop_column('cars', 'mileage')
    op.drop_column('cars', 'doors')
    op.drop_column('cars', 'seats')
    op.drop_column('cars', 'fuel_type')
    op.drop_column('cars', 'transmission')
    op.drop_column('cars', 'postcode')
    op.drop_column('cars', 'city')
    # ### end Alembic commands ###
